version: "2"
services:
  oauth2:
    image: rlkamradt/oauth2service
    env_file:
      - ~/.secrets/auth.env
    ports:
      - "8888:8080"
    networks:
      - network
  idapi:
    build: .
    env_file:
      - ~/.secrets/auth.env
    ports:
      - "3000:3000"
    networks:
      - network
  intidapi:
    build: .
    env_file:
      - ~/.secrets/auth.env
    environment:
      - NO_AUTH=true
    ports:
      - "3001:3000"
    networks:
      - network
  redis:
    image: redis:alpine
    networks:
      - network
networks:
  network:
